artifact_location: file:///home/pranavtyagi/ML_Mastery/01_Supervised/Linear_Regression/projects/HousePrice/scripts/mlartifacts/146909752645534054
creation_time: 1772371838129
experiment_id: '146909752645534054'
last_update_time: 1772371838129
lifecycle_stage: active
name: fsds-train
