artifact_location: file:///home/pranavtyagi/ML_Mastery/01_Supervised/Linear_Regression/projects/HousePrice/scripts/mlartifacts/0
creation_time: 1772371838078
experiment_id: '0'
last_update_time: 1772371838078
lifecycle_stage: active
name: Default
