artifact_uri: file:///home/pranavtyagi/ML_Mastery/01_Supervised/Linear_Regression/projects/HousePrice/mlartifacts/860816234375370280/541b91f1a6ee4f408191ab1f42cafc59/artifacts
end_time: 1769937275471
entry_point_name: ''
experiment_id: '860816234375370280'
lifecycle_stage: active
run_id: 541b91f1a6ee4f408191ab1f42cafc59
run_name: bustling-midge-532
source_name: ''
source_type: 4
source_version: ''
start_time: 1769937275451
status: 3
tags: []
user_id: pranavtyagi
