artifact_location: file:///home/pranavtyagi/ML_Mastery/01_Supervised/Linear_Regression/projects/HousePrice/mlartifacts/860816234375370280
creation_time: 1769937274261
experiment_id: '860816234375370280'
last_update_time: 1769937274261
lifecycle_stage: active
name: fsds-ingest-data
