artifact_location: file:///home/pranavtyagi/ML_Mastery/01_Supervised/Linear_Regression/projects/HousePrice/mlartifacts/591315502942322130
creation_time: 1769937868634
experiment_id: '591315502942322130'
last_update_time: 1769937868634
lifecycle_stage: active
name: fsds-train
