artifact_location: file:///home/pranavtyagi/ML_Mastery/01_Supervised/Linear_Regression/projects/HousePrice/mlartifacts/994750409383161357
creation_time: 1769938145856
experiment_id: '994750409383161357'
last_update_time: 1769938145856
lifecycle_stage: active
name: fsds-score
