artifact_uri: file:///home/pranavtyagi/ML_Mastery/01_Supervised/Linear_Regression/projects/HousePrice/mlartifacts/591315502942322130/f2835ee7067f4102b9c3943bdff9590e/artifacts
end_time: 1769937911155
entry_point_name: ''
experiment_id: '591315502942322130'
lifecycle_stage: active
run_id: f2835ee7067f4102b9c3943bdff9590e
run_name: shivering-dolphin-16
source_name: ''
source_type: 4
source_version: ''
start_time: 1769937907073
status: 3
tags: []
user_id: pranavtyagi
