artifact_uri: file:///home/pranavtyagi/ML_Mastery/01_Supervised/Linear_Regression/projects/HousePrice/mlartifacts/994750409383161357/f57fb7a1bb11405bb3cba3e73a64ab9e/artifacts
end_time: 1769938146372
entry_point_name: ''
experiment_id: '994750409383161357'
lifecycle_stage: active
run_id: f57fb7a1bb11405bb3cba3e73a64ab9e
run_name: agreeable-stork-261
source_name: ''
source_type: 4
source_version: ''
start_time: 1769938146364
status: 3
tags: []
user_id: pranavtyagi
