artifact_uri: file:///home/pranavtyagi/ML_Mastery/01_Supervised/Linear_Regression/projects/HousePrice/scripts/mlartifacts/146909752645534054/c93b0faa0a1546d0bd9d4b58c56bbcd8/artifacts
end_time: 1772373636515
entry_point_name: ''
experiment_id: '146909752645534054'
lifecycle_stage: active
run_id: c93b0faa0a1546d0bd9d4b58c56bbcd8
run_name: bouncy-bug-877
source_name: ''
source_type: 4
source_version: ''
start_time: 1772373632919
status: 3
tags: []
user_id: pranavtyagi
